export const mcfToExchange = {
    'AAVUSD.mcf': {bybit:'AAVEUSDT', binance:'AAVEUSDT', okx:'AAVE-USDT-SWAP', coinbase:'AAVE-PERP'},
    'ADAUSD.mcf': {bybit:'ADAUSDT', binance:'ADAUSDT', okx:'ADA-USDT-SWAP', coinbase: 'ADA-PERP'},
    'ALGUSD.mcf': {bybit:'ALGOUSDT', binance:'ALGOUSDT', okx:'ALGO-USDT-SWAP', coinbase: 'ALGO-PERP'},
    'ANKUSD.mcf': {bybit:'ANKRUSDT', binance:'ANKRUSDT', okx:'', coinbase: ''},
    'APEUSD.mcf': {bybit:'APEUSDT', binance:'APEUSDT', okx:'APE-USDT-SWAP', coinbase: 'APE-PERP'},
    'ATMUSD.mcf': {bybit:'ATOMUSDT', binance:'ATOMUSDT', okx:'ATOM-USDT-SWAP', coinbase: 'ATOM-PERP'},
    'AVAUSD.mcf': {bybit:'AVAXUSDT', binance:'AVAXUSDT', okx:'AVAX-USDT-SWAP', coinbase: 'AVAX-PERP'},
    'AXSUSD.mcf': {bybit:'AXSUSDT', binance:'AXSUSDT', okx:'AXS-USDT-SWAP', coinbase: ''},
    'BATUSD.mcf': {bybit:'BATUSDT', binance:'BATUSDT', okx:'BAT-USDT-SWAP', coinbase: ''},
    'BCHUSD.mcf': {bybit:'BCHUSDT', binance:'BCHUSDT', okx:'BCH-USDT-SWAP', coinbase: 'BCH-PERP'},
    'BNBUSD.mcf': {bybit:'BNBUSDT', binance:'BNBUSDT', okx:'BNB-USDT-SWAP', coinbase: ''},
    'BTCUSD.mcf': {bybit:'BTCUSDT', binance:'BTCUSDT', okx:'BTC-USDT-SWAP', coinbase: 'BTC-PERP'},
    'CHZUSD.mcf': {bybit:'CHZUSDT', binance:'CHZUSDT', okx:'CHZ-USDT-SWAP', coinbase: ''},
    'COMUSD.mcf': {bybit:'COMPUSDT', binance:'COMPUSDT', okx:'COMP-USDT-SWAP', coinbase: ''},
    'COTUSD.mcf': {bybit:'COTIUSDT', binance:'COTIUSDT', okx:'', coinbase:''},
    'DOGUSD.mcf': {bybit:'DOGEUSDT', binance:'DOGEUSDT', okx:'DOGE-USDT-SWAP', coinbase:'DOGE-PERP'},
    'DOTUSD.mcf': {bybit:'DOTUSDT', binance:'DOTUSDT', okx:'DOT-USDT-SWAP', coinbase: 'DOT-PERP'},
    'DSHUSD.mcf': {bybit:'DASHUSDT', binance:'DASHUSDT', okx:'', coinbase: ''},
    'ENJUSD.mcf': {bybit:'ENJUSDT', binance:'ENJUSDT', okx:'ENJ-USDT-SWAP', coinbase: ''},
    'EOSUSD.mcf': {bybit:'EOSUSDT', binance:'EOSUSDT', okx:'EOS-USDT-SWAP', coinbase: 'EOS-PERP'},
    'ETCUSD.mcf': {bybit:'ETCUSDT', binance:'ETCUSDT', okx:'ETC-USDT-SWAP', coinbase: 'ETC-PERP'},
    'ETHUSD.mcf': {bybit:'ETHUSDT', binance:'ETHUSDT', okx:'ETH-USDT-SWAP', coinbase: 'ETH-PERP'},
    'FTMUSD.mcf': {bybit:'SONICUSDT', binance:'SONICUSDT', okx:'SONIC-USDT-SWAP', coinbase: ''},
    'GMTUSD.mcf': {bybit:'GMTUSDT', binance:'GMTUSDT', okx:'GMT-USDT-SWAP', coinbase:''},
    'GRTUSD.mcf': {bybit:'GRTUSDT', binance:'GRTUSDT', okx:'GRT-USDT-SWAP', coinbase:''},
    'IMXUSD.mcf': {bybit:'IMXUSDT', binance:'IMXUSDT', okx:'IMX-USDT-SWAP', coinbase:'IMX-PERP'},
    'INCUSD.mcf': {bybit:'1INCHUSDT', binance:'1INCHUSDT', okx:'1INCH-USDT-SWAP', coinbase: ''},
    'IOSUSD.mcf': {bybit:'IOSTUSDT', binance:'IOSTUSDT', okx:'IOST-USDT-SWAP', coinbase: ''},
    'IOTUSD.mcf': {bybit:'IOTAUSDT', binance:'IOTAUSDT', okx:'IOTA-USDT-SWAP', coinbase: ''},
    'KSMUSD.mcf': {bybit:'KSMUSDT', binance:'KSMUSDT', okx:'KSM-USDT-SWAP', coinbase: ''},
    'LNKUSD.mcf': {bybit:'LINKUSDT', binance:'LINKUSDT', okx:'LINK-USDT-SWAP',coinbase:'LINK-PERP'},
    'LPTUSD.mcf': {bybit:'LPTUSDT', binance:'LPTUSDT', okx:'LPT-USDT-SWAP', coinbase: ''},
    'LRCUSD.mcf': {bybit:'LRCUSDT', binance:'LRCUSDT', okx:'LRC-USDT-SWAP', coinbase: ''},
    'LTCUSD.mcf': {bybit:'LTCUSDT', binance:'LTCUSDT', okx:'LTC-USDT-SWAP',coinbase:'LTC-PERP'},
    'MANUSD.mcf': {bybit:'MANAUSDT', binance:'MANAUSDT', okx:'MANA-USDT-SWAP', coinbase: ''},
    'MKRUSD.mcf': {bybit:'MKRUSDT', binance:'MKRUSDT', okx:'MKR-USDT-SWAP', coinbase: 'MKR-PERP'},
    'NEOUSD.mcf': {bybit:'NEOUSDT', binance:'NEOUSDT', okx:'NEO-USDT-SWAP', coinbase: ''},
    'NERUSD.mcf': {bybit:'NEARUSDT', binance:'NEARUSDT', okx:'NEAR-USDT-SWAP', coinbase:'NEAR-PERP'},
    'ONTUSD.mcf': {bybit:'ONTUSDT', binance:'ONTUSDT', okx:'ONT-USDT-SWAP',coinbase: ''},
    'PEPUSD.mcf': {bybit:'PEOPLEUSDT', binance:'PEOPLEUSDT', okx:'PEOPLE-USDT-SWAP',coinbase:''},
    'QTMUSD.mcf': {bybit:'QTUMUSDT', binance:'QTUMUSDT', okx:'QTUM-USDT-SWAP', coinbase:''},
    'RVNUSD.mcf': {bybit:'RVNUSDT', binance:'RVNUSDT', okx:'RVN-USDT-SWAP',coinbase: ''},
    'SANUSD.mcf': {bybit:'SANDUSDT', binance:'SANDUSDT', okx:'SAND-USDT-SWAP', coinbase:''},
    'SHBUSD.mcf': {bybit:'SHIB1000USDT', binance:'1000SHIBUSDT', okx:'SHIB-USDT-SWAP',coinbase:'SAND-PERP'},
    'SKLUSD.mcf': {bybit:'SKLUSDT', binance:'SKLUSDT', okx:'', coinbase:''},
    'SNXUSD.mcf': {bybit:'SNXUSDT', binance:'SNXUSDT', okx:'SNX-USDT-SWAP',coinbase:''},
    'SOLUSD.mcf': {bybit:'SOLUSDT', binance:'SOLUSDT', okx:'SOL-USDT-SWAP', coinbase:'SOL-PERP'},
    'STOUSD.mcf': {bybit:'STORJUSDT', binance:'STORJUSDT', okx:'STORJ-USDT-SWAP',coinbase: '' },
    'SUSUSD.mcf': {bybit:'SUSHIUSDT', binance:'SUSHIUSDT', okx:'SUSHI-USDT-SWAP', coinbase: ''},
    'SXPUSD.mcf': {bybit:'SXPUSDT', binance:'SXPUSDT', okx:'', coinbase:''},
    'TETUSD.mcf': {bybit:'THETAUSDT', binance:'THETAUSDT', okx:'THETA-USDT-SWAP', coinbase:''},
    'TRXUSD.mcf': {bybit:'TRXUSDT', binance:'TRXUSDT', okx:'TRX-USDT-SWAP', coinbase:''},
    'UNIUSD.mcf': {bybit:'UNIUSDT', binance:'UNIUSDT', okx:'UNI-USDT-SWAP', coinbase:'UNI-PERP'},
    'WOOUSD.mcf': {bybit:'WOOUSDT', binance:'WOOUSDT', okx:'WOO-USDT-SWAP', coinbase:''},
    'XLMUSD.mcf': {bybit:'XLMUSDT', binance:'XLMUSDT', okx:'XLM-USDT-SWAP', coinbase: 'XLM-PERP'},
    'XRPUSD.mcf': {bybit:'XRPUSDT', binance:'XRPUSDT', okx:'XRP-USDT-SWAP',coinbase: 'XRP-PERP'},
    'ZECUSD.mcf': {bybit:'ZECUSDT', binance:'ZECUSDT', okx:'', coinbase: ''},
    'ZILUSD.mcf': {bybit:'ZILUSDT', binance:'ZILUSDT', okx:'ZIL-USDT-SWAP',coinbase:''},
    'ALIUSD.mcf': {bybit:'ALICEUSDT', binance:'ALICEUSDT', okx:'', coinbase:''},
    'CEOUSD.mcf': {bybit:'CELOUSDT', binance:'CELOUSDT', okx:'CELO-USDT-SWAP', coinbase:''},
    'CHRUSD.mcf': {bybit:'CHRUSDT', binance:'CHRUSDT', okx:'', coinbase:''},
    'CNEUSD.mcf': {bybit:'C98USDT', binance:'C98USDT', okx:'',coinbase:''},
    'CRVUSD.mcf': {bybit:'CRVUSDT', binance:'CRVUSDT', okx:'CRV-USDT-SWAP', coinbase: 'CRV-PERP'},
    'DYDUSD.mcf': {bybit:'DYDXUSDT', binance:'DYDXUSDT', okx:'DYDX-USDT-SWAP', coinbase:''},
    'FILUSD.mcf': {bybit:'FILUSDT', binance:'FILUSDT', okx:'FIL-USDT-SWAP',coinbase:'FIL-PERP'},
    'FLWUSD.mcf': {bybit:'FLOWUSDT', binance:'FLOWUSDT', okx:'FLOW-USDT-SWAP', coinbase:'FLOW-PERP'},
    'GALUSD.mcf': {bybit:'GALAUSDT', binance:'GALAUSDT', okx:'GALA-USDT-SWAP',coinbase:''},
    'KAVUSD.mcf': {bybit:'KAVAUSDT', binance:'KAVAUSDT', okx:'',coinbase:''},
    'KNCUSD.mcf': {bybit:'KNCUSDT', binance:'KNCUSDT', okx:'KNC-USDT-SWAP', coinbase: ''},
    'OMGUSD.mcf': {bybit:'OMGUSDT', binance:'OMGUSDT', okx:'', coinbase: ''},
    'ONEUSD.mcf': {bybit:'ONEUSDT', binance:'ONEUSDT', okx:'ONE-USDT-SWAP',coinbase:''},
    'RENUSD.mcf': {bybit:'RENUSDT', binance:'', okx:'',coinbase:''},
    'RSRUSD.mcf': {bybit:'RSRUSDT', binance:'RSRUSDT', okx:'RSR-USDT-SWAP',coinbase:''},
    'VECUSD.mcf': {bybit:'VETUSDT', binance:'VETUSDT', okx:'', coinbase:''},
    'XEMUSD.mcf': {bybit:'XEMUSDT', binance:'', okx:'', coinbase:''},
    'XMRUSD.mcf': {bybit:'XMRUSDT', binance:'XMRUSDT', okx:'', coinbase:''},
    'XTZUSD.mcf': {bybit:'XTZUSDT', binance:'XTZUSDT', okx:'XTZ-USDT-SWAP', coinbase:''},
    'ZENUSD.mcf': {bybit:'ZENUSDT', binance:'ZENUSDT', okx:'', coinbase:''},
    'ZRXUSD.mcf': {bybit:'ZRXUSDT', binance:'ZRXUSDT', okx:'ZRX-USDT-SWAP', coinbase:''},
    'AGLDUSD.mcf': {bybit:'AGLDUSDT', binance:'AGLDUSDT', okx:'AGLD-USDT-SWAP', coinbase:''},
    'BALUSD.mcf': {bybit:'BALUSDT', binance:'BALUSDT', okx:'BAL-USDT-SWAP', coinbase:''},
    'BNTUSD.mcf': {bybit:'BNTUSDT', binance:'BNTUSDT', okx:'BNT-USDT-SWAP', coinbase:''},
    'BSVUSD.mcf': {bybit:'BSVUSDT', binance:'BSVUSDT', okx:'BSV-USDT-SWAP', coinbase:''},
    'COREUSD.mcf': {bybit:'COREUSDT', binance:'', okx:'CORE-USDT-SWAP', coinbase:''},
    'CTCUSD.mcf': {bybit:'CTCUSDT', binance:'', okx:'', coinbase:''},
    'EGLDUSD.mcf': {bybit:'EGLDUSDT', binance:'EGLDUSDT', okx:'EGLD-USDT-SWAP', coinbase:''},
    'FITFIUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'FLOKIUSD.mcf': {bybit:'1000FLOKIUSDT', binance:'1000FLOKIUSDT', okx:'FLOKI-USDT-SWAP', coinbase:''},
    'GMXUSD.mcf': {bybit:'GMXUSDT', binance:'GMXUSDT', okx:'GMX-USDT-SWAP', coinbase:''},
    'LDOUSD.mcf': {bybit:'LDOUSDT', binance:'LDOUSDT', okx:'LDO-USDT-SWAP', coinbase:''},
    'MASKUSD.mcf': {bybit:'MASKUSDT', binance:'MASKUSDT', okx:'MASK-USDT-SWAP', coinbase:''},
    'MEMEUSD.mcf': {bybit:'MEMEUSDT', binance:'MEMEUSDT', okx:'MEME-USDT-SWAP', coinbase:''},
    'ORBSUSD.mcf': {bybit:'ORBSUSDT', binance:'', okx:'ORBS-USDT-SWAP', coinbase:''},
    'SSVUSD.mcf': {bybit:'SSVUSDT', binance:'SSVUSDT', okx:'SSV-USDT-SWAP', coinbase:''},
    'TIAUSD.mcf': {bybit:'TIAUSDT', binance:'TIAUSDT', okx:'TIA-USDT-SWAP', coinbase:''},
    'TONUSD.mcf': {bybit:'TONUSDT', binance:'TONUSDT', okx:'TON-USDT-SWAP', coinbase:''},
    'WAXPUSD.mcf': {bybit:'WAXPUSDT', binance:'WAXPUSDT', okx:'WAXP-USDT-SWAP', coinbase:''},
    'APTUSD.mcf': {bybit:'APTUSDT', binance:'APTUSDT', okx:'APT-USDT-SWAP', coinbase:''},
    'PNUTUSD.mcf': {bybit:'PNUTUSDT', binance:'PNUTUSDT', okx:'PNUT-USDT-SWAP', coinbase:''},
    'GRASSUSD.mcf': {bybit:'GRASSUSDT', binance:'GRASSUSDT', okx:'GRASS-USDT-SWAP', coinbase:''},
    'BOMEUSD.mcf': {bybit:'BOMEUSDT', binance:'BOMEUSDT', okx:'BOME-USDT-SWAP', coinbase:''},
    'WIFUSD.mcf': {bybit:'WIFUSDT', binance:'WIFUSDT', okx:'WIF-USDT-SWAP', coinbase:''},
    'AEVOUSD.mcf': {bybit:'AEVOUSDT', binance:'AEVOUSDT', okx:'AEVO-USDT-SWAP', coinbase:''},
    'LUCEUSD.mcf': {bybit:'LUCEUSDT', binance:'', okx:'', coinbase:''},
    'JUPUSD.mcf': {bybit:'JUPUSDT', binance:'JUPUSDT', okx:'JUP-USDT-SWAP', coinbase:''},
    'WATUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'CARVUSD.mcf': {bybit:'CARVUSDT', binance:'', okx:'', coinbase:''},
    'CLVUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'MICHIUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'ENAUSD.mcf': {bybit:'ENAUSDT', binance:'ENAUSDT', okx:'', coinbase:''},
    'LQTYUSD.mcf': {bybit:'LQTYUSDT', binance:'LQTYUSDT', okx:'LQTY-USDT-SWAP', coinbase:''},
    'UMAUSD.mcf': {bybit:'UMAUSDT', binance:'UMAUSDT', okx:'UMA-USDT-SWAP', coinbase:''},
    'JTOUSD.mcf': {bybit:'JTOUSDT', binance:'JTOUSDT', okx:'JTO-USDT-SWAP', coinbase:'JTO-PERP'},
    'PYTHUSD.mcf': {bybit:'PYTHUSDT', binance:'PYTHUSDT', okx:'PYTH-USDT-SWAP', coinbase:''},
    'SLOPUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'OMNIUSD.mcf': {bybit:'OMNIUSDT', binance:'OMNIUSDT', okx:'', coinbase:''},
    'ARDRUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'BAKEUSD.mcf': {bybit:'BAKEUSDT', binance:'BAKEUSDT', okx:'', coinbase:''},
    'DUSKUSD.mcf': {bybit:'DUSKUSDT', binance:'DUSKUSDT', okx:'', coinbase:''},
    'ZETAUSD.mcf': {bybit:'ZETAUSDT', binance:'ZETAUSDT', okx:'ZETA-USDT-SWAP', coinbase:''},
    'GAMEUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'CVCUSD.mcf': {bybit:'CVCUSDT', binance:'', okx:'CVC-USDT-SWAP', coinbase:''},
    'GOATUSD.mcf': {bybit:'GOATUSDT', binance:'GOATUSDT', okx:'GOAT-USDT-SWAP', coinbase:''},
    'COWUSD.mcf': {bybit:'COWUSDT', binance:'COWUSDT', okx:'', coinbase:''},
    'SWEUSD.mcf': {bybit:'SWELLUSDT', binance:'SWELLUSDT', okx:'SWELL-USDT-SWAP', coinbase:''},
    'CETUSD.mcf': {bybit:'CETUSUSDT', binance:'CETUSUSDT', okx:'CETUS-USDT-SWAP', coinbase:''},
    'RIFUSD.mcf': {bybit:'RIFUSDT', binance:'RIFUSDT', okx:'', coinbase:''},
    'SUIUSD.mcf': {bybit:'SUIUSDT', binance:'SUIUSDT', okx:'SUI-USDT-SWAP', coinbase:''},
    'BANUSD.mcf': {bybit:'BANUSDT', binance:'BANUSDT', okx:'', coinbase:''},
    'MOCUSD.mcf': {bybit:'MOCAUSDT', binance:'MOCAUSDT', okx:'', coinbase:''},
    'ATHUSD.mcf': {bybit:'ATHUSDT', binance:'', okx:'ATH-USDT-SWAP', coinbase:''},
    'ARBUSD.mcf': {bybit:'ARBUSDT', binance:'ARBUSDT', okx:'ARB-USDT-SWAP', coinbase:''},
    'WLDUSD.mcf': {bybit:'WLDUSDT', binance:'WLDUSDT', okx:'WLD-USDT-SWAP', coinbase:''},
    'POPUSD.mcf': {bybit:'POPCAT', binance:'POPCATUSDT', okx:'POPCAT-USDT-SWAP', coinbase:''},
    'KAIUSD.mcf': {bybit:'KAIAUSDT', binance:'', okx:'', coinbase:''},
    'XCHUSD.mcf': {bybit:'XCHUSDT', binance:'', okx:'XCH-USDT-SWAP', coinbase:''},
    'BFCUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'EGPUSD.mcf': {bybit:'', binance:'', okx:'', coinbase:''},
    'WENUSD.mcf': {bybit:'10000WENUSDT', binance:'', okx:'', coinbase:''},
    'SAGAUSD.mcf': {bybit:'SAGAUSDT', binance:'SAGAUSDT', okx:'', coinbase:''},
    'FXSUSD.mcf': {bybit:'FXSUSDT', binance:'FXSUSDT', okx:'FXS-USDT-SWAP', coinbase:''},
    'LUNAUSD.mcf': {bybit:'LUNA2USDT', binance:'LUNA2USDT', okx:'LUNA-USDT-SWAP', coinbase:''},
    'YGGUSD.mcf': {bybit:'YGGUSDT', binance:'YGGUSDT', okx:'YGG-USDT-SWAP', coinbase:''},
    'CKBUSD.mcf': {bybit:'CKBUSDT', binance:'CKBUSDT', okx:'', coinbase:''},
    'DOPUSD.mcf': {bybit:'DOP1USDT', binance:'', okx:'', coinbase:''}
};

// Exchange to MCF mappings (reverse mapping)
export const exchangeToMcf = {
    bybit: generateExchangeMapping('bybit'),
    binance: generateExchangeMapping('binance'),
    okx: generateExchangeMapping('okx'),
    coinbase: generateExchangeMapping('coinbase')
};

// Helper function to generate exchange mapping
function generateExchangeMapping(exchangeName) {
    return Object.entries(mcfToExchange).reduce((acc, [mcfSymbol, exchanges]) => {
        // Only add to accumulator if the exchange symbol exists and is not empty
        if (exchanges[exchangeName] && exchanges[exchangeName] !== '') {
            acc[exchanges[exchangeName]] = mcfSymbol;
        }
        return acc;
    }, {});
}
console.log(exchangeToMcf)